app1/urls.py
from django.urls import path
from app1.views import *
app_name='app1'
urlpatterns=[
    path('pow/',Pow,name='pow'),
    path('Check/',Check,name='Check'),
    
]

project_2/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls'))
]

app1/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    first_name=models.CharField(max_length=100)
    last_name=models.CharField(max_length=100)
    age=models.IntegerField()

    def __str__(self):
        return self.first_name

app1/forms.py
from django import forms

from app1.models import *

class Creation(forms.ModelForm):
    class Meta:
        model=Question
        fields='__all__'
        

app1/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from app1.models import *
from app1.forms import *
# Create your views here.
# def Hello(request):
#     return HttpResponse('<h1>Hello BUdddy!!!!</h1>')

def Check(request):
    form=Creation()
    if request.method == 'POST':
        form=Creation(request.POST)
        if form.is_valid():
            form.save()
            return render(request,'message.html')

    d={'form' : form}
    return render(request,'form.html',d)
def Pow(request):
    met=Question.objects.all()
    d={'met':met}
    return render(request,'index.html',d)

templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <title>Forms</title>
</head>

<body>
    <div class="form">
        <form method="POST" action="">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="Submit">
            <input type="reset" value="Reset">
            <img src="{% static 'images/download.html'}" alt="m_letter">
    
        </form>
    </div>
</body>

</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Table</title>
</head>
<body>
    <table>
        <tr>
            <td>First_name</td>
            <td>Last_name</td>
            <td>age</td>
        </tr>
        {% for i in met %}
        <tr>
            <td>{{i.first_name}}</td>
            <td>{{i.last_name}}</td>
            <td>{{i.age}}</td>
        </tr>
        {% endfor %}
    </table>
</body>
</html>

templates/message.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Message</title>
</head>
<body>
    <h1>
        record Inserted successfully
    </h1>
    <a href="{% url 'app1:Check' %}"> go back</a>
</body>
</html>